services:
  calorie-tracker-frontend:
    build: .
    container_name: calorie-tracker-frontend
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/fynn-koch.de-0001/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/fynn-koch.de-0001/privkey.pem:/etc/nginx/ssl/privkey.pem
    restart: unless-stopped
